spring.mvc.view:
  prefix: /WEB-INF/view/
  suffix: .jsp

logging.level:
  org.apache.tomcat: DEBUG
  org.apache.tomcat.util: INFO
  org.jetty.servlet: DEBUG
  org.springframework: DEBUG
  org.springframework.beans.factory: INFO
  org.springframework.boot.autoconfigure.logging: INFO
